spring.application.name=bookstoremiska
spring.h2.console.enabled=true
# VERKKOSELAIMESSA KAYTETTAVA TIETOKANNAN SELAUS GUI
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.show-sql=true

